spring.application.name=auth_service
server.port=${PORT:8080}

aws.ses.sender-email=${EMAIL_SES}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

token-secret=${TOKEN_SECRET}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.connect-retries=5

spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

url-login-google=${URL_LOGIN}
url-register-google=${URL_REGISTER}

spring.jpa.open-in-view=false
allowed.origins=${ALLOWED_ORIGINS}
management.endpoints.web.exposure.include=health