spring.application.name=auth_service
server.port=${PORT:8080}

## Configura\u00E7\u00F5es de envio de e-mails
aws.ses.sender-email=${EMAIL_SES}

# Configura\u00E7\u00F5es login Google
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

# Configura\u00E7\u00E3o Token Spring Security
token-secret=${TOKEN_SECRET}

# Configura\u00E7\u00F5es do banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.connect-retries=5

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none