spring.application.name=auth_service
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.connect-retries=5
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

token-secret=${TOKEN_SECRET:local-dev-secret}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:local-id}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:local-secret}
url-login-google=${URL_LOGIN:http://localhost:8080/auth/login/google/authorized}
url-register-google=${URL_REGISTER:http://localhost:8080/auth/register/google/authorized}

aws.ses.sender-email=${EMAIL_SES:teste@silvestre.local}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}

allowed.origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true