spring.application.name=order_service
server.port=${PORT:8082}

api.security.token.secret=${token-secret}

product.service.url=${url-product-service}

spring.datasource.url=${url-database}
spring.datasource.username=${username-database}
spring.datasource.password=${password-database}
aws.sqs.queue.order-created=${sqs-order}
spring.cloud.aws.region.static=us-east-1

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true