spring.application.name=order_service
server.port=${PORT:8082}

# Banco
spring.datasource.url=jdbc:postgresql://db-order:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT mesma secret do auth-service
token-secret=${token-secret:local-dev-secret-trocar-em-producao}

# URL do product-service (nome do container no compose)
url-product-service=${url-product-service:http://product-service:8081}

# SQS aponta para LocalStack
aws.sqs.queue.order-created=${sqs-order:order-created}
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=${SPRING_CLOUD_AWS_SQS_ENDPOINT:http://localstack:4566}
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

spring.flyway.connect-retries=5
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true