spring.application.name=product-service
server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.connect-retries=5

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

token-secret=${TOKEN_SECRET}
aws-bucket-name=${AWS_BUCKET_NAME}

aws.sqs.queue.order-created=${SQS_ORDER_QUEUE}

aws.region=${AWS_REGION}

aws_access_key=${AWS_ACCESS_KEY_ID}
aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}

spring.jpa.open-in-view=false
allowed.origins=${ALLOWED_ORIGINS}
management.endpoints.web.exposure.include=health