spring.application.name=product-service
server.port=8081

# Banco
spring.datasource.url=jdbc:postgresql://db-product:5432/product_db
spring.datasource.username=product_user
spring.datasource.password=product_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.connect-retries=5
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true

# JWT
token-secret=${TOKEN_SECRET}

# AWS S3 aponta para o LocalStack em vez da AWS real
aws-bucket-name=${AWS_BUCKET_NAME:silvestre-produtos}
aws.region=${AWS_REGION:us-east-1}

# Endpoint override: faz o S3Client apontar para o LocalStack
#spring.cloud.aws.sqs.endpoint=${AWS_ENDPOINT_OVERRIDE:http://localstack:4566}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:test}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:test}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}