spring.application.name=product-service
server.port=${PORT:8081}

# Configura\u00E7\u00F5es do banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.connect-retries=5

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none

# Configura\u00E7\u00E3o Token Spring Security
token-secret=${TOKEN_SECRET}

#Configura\u00E7\u00F5es AWS
aws-bucket-name=${AWS_BUCKET_NAME}